name: 🐍 Setup Cylc Conda
description: Install miniforge, cylc/rose packages and setup wrapper script
inputs:
  env-path:
    required: true
    type: string
    default: 'cylc-src/bioreactor-workflow/envs/cylc.yml'

runs:
  using: composite
  steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: false
        activate-environment: cylc
        miniforge-version: latest
        environment-file: ${{ inputs.env-path }}
    
    # use login shell for conda activation after setup-miniconda
    - name: add graphviz
      shell: bash -el {0}
      run: |
        conda install -y graphviz
    - name: setup cylc wrapper script
      shell: bash -el {0}
      run: |
        CONDA_ENVS=${CONDA}/envs
        WRAPPER_DIR=/usr/local/bin
        cylc get-resources cylc ${WRAPPER_DIR} && chmod +x ${WRAPPER_DIR}/cylc
        sed -i 's|^CYLC_HOME_ROOT=.*|CYLC_HOME_ROOT=${CONDA_ENVS}|' ${WRAPPER_DIR}/cylc
        ln -s ${WRAPPER_DIR}/cylc ${WRAPPER_DIR}/rose
        