name: 🧹 Cylc Lint and Validate Workflow

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/cylc-lint-validate.yml'
      - 'cylc-src/**.cylc'
  push:
    branches: [main]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cylc-validate:
    name: Validate Cylc files
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -eul {0}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-conda-cylc
        with:
          env-path: 'cylc-src/bioreactor-workflow/envs/cylc.yml'
      - name: cylc lint
        run: |
          cylc lint ./cylc-src/bioreactor-workflow
      - name: cylc validate
        run: |
          cylc validate ./cylc-src/bioreactor-workflow