name: 🧹 Cylc Lint and Validate Workflow

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/cylc-lint-validate.yml'
      - '.github/actions/install-conda-cylc/action.yml'
      - 'cylc-src/**.cylc'
  push:
    branches: [main]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cylc-validate:
    name: Validate Cylc files
    runs-on: ubuntu-latest
    env:
      conda_env_file: 'cylc-src/bioreactor-workflow/envs/cylc.yml'
      workflow_path: './cylc-src/bioreactor-workflow'
    defaults:
      run:
        shell: bash -eul {0}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-conda-cylc
        with:
          env-path: ${{ env.conda_env_file }}
      - name: cylc lint
        run: |
          cylc lint -v ${workflow_path}
      - name: cylc validate
        run: |
          cylc validate -v ${workflow_path}