name: 🔗 Markdown URL Checker

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: 'README.md'